apiVersion: v1
kind: Service
metadata:
  name: {{ include "governance-hub.appName" . }}
  namespace: {{ include "governance-hub.namespace" . }}
  labels:
    {{- include "governance-hub.labels" . | nindent 4 }}
    component: app
spec:
  type: {{ .Values.service.app.type }}
  ports:
  - port: {{ .Values.service.app.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "governance-hub.selectorLabels" . | nindent 4 }}
    component: app
