apiVersion: v1
kind: Service
metadata:
  name: {{ include "governance-hub.nginxName" . }}
  namespace: {{ include "governance-hub.namespace" . }}
  labels:
    {{- include "governance-hub.labels" . | nindent 4 }}
    component: nginx
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
  - port: {{ .Values.service.nginx.ports.http }}
    targetPort: {{ .Values.nginx.ports.http }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.nginx.ports.https }}
    targetPort: {{ .Values.nginx.ports.https }}
    protocol: TCP
    name: https
  selector:
    {{- include "governance-hub.selectorLabels" . | nindent 4 }}
    component: nginx
